zhuartcc/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.views.decorators.clickjacking import xframe_options_sameorigin
from django.views.static import serve

from apps.administration import views as administration
from apps.api import views as api
from apps.event import views as event
from apps.feedback import views as feedback
from apps.pilots import views as pilots
from apps.resource import views as resource
from apps.training import views as training
from apps.uls import views as uls
from apps.user import views as user
from apps.views import views as views
from apps.visit import views as visit

urlpatterns = [
    # Administration
    path('admin/', administration.view_admin_panel, name='admin'),
    path('admin/log/', administration.view_action_log, name='log'),
    path('admin/transfers/', administration.view_transfers, name='transfer_requests'),
    path('admin/announcement/', administration.view_announcement, name='announcement'),
    path('admin/broadcast/', administration.view_broadcast, name='broadcast'),

    # API
    path('statistics/', api.view_statistics, name='statistics'),
    path('api/vatis/', api.atis, name='update_atis'),
    path('api/vatis/<str:icao>/', api.atis_icao, name='get_atis'),
    path('api/tmu/', api.tmu, name='tmu'),
    path('api/tmu/<int:notice_id>/delete/', api.delete_tmu, name='delete_tmu'),

    # Event
    path('events/', event.view_all_events, name='events'),
    path('events/archived/', event.view_archived_events, name='archived_events'),
    path('events/new/', event.add_event, name='new_event'),
    path('events/score/', event.view_event_score, name='event_score'),
    path('events/score/<int:cid>/', event.view_event_score, name='event_score_cid'),
    path('events/<int:event_id>/', event.view_event, name='event'),
    path('events/<int:event_id>/edit/', event.edit_event, name='edit_event'),
    path('events/<int:event_id>/delete/', event.delete_event, name='delete_event'),
    path('events/<int:event_id>/add/', event.add_position, name='add_position'),
    path('events/<int:event_id>/embedpositions/', event.embed_positions, name='embed_positions'),
    path('events/position/<int:position_id>/request/', event.request_position, name='request_position'),
    path('events/position/<int:request_id>/unrequest/', event.unrequest_position, name='unrequest_position'),
    path('events/position/<int:request_id>/assign/', event.assign_position, name='assign_position'),
    path('events/position/<int:position_id>/assign/<int:cid>/', event.manual_assign, name='manual_assign_position'),
    path('events/position/<int:position_id>/unassign/', event.unassign_position, name='unassign_position'),
    path('events/position/<int:position_id>/delete/', event.delete_position, name='delete_position'),
    path('events/presets/', event.view_presets, name='presets'),
    path('events/presets/new/', event.add_preset, name='new_preset'),
    path('events/presets/edit/<int:preset_id>/', event.edit_preset, name='edit_preset'),
    path('events/presets/delete/<int:preset_id>/', event.delete_preset, name='delete_preset'),

    # Feedback
    path('feedback/', feedback.add_feedback, name='feedback'),
    path('feedback/approval/', feedback.view_feedback_approval, name='feedback_approval'),
    path('feedback/<int:feedback_id>/approve/', feedback.approve_feedback, name='accept_feedback'),
    path('feedback/<int:feedback_id>/reject/', feedback.reject_feedback, name='reject_feedback'),

    # Pilots
    path('map/', pilots.view_artcc_map, name='map'),
    path('scenery/', pilots.view_scenery, name='scenery'),
    path('scenery/new/', pilots.add_scenery, name='new_scenery'),
    path('scenery/<int:scenery_id>/edit/', pilots.edit_scenery, name='edit_scenery'),
    path('scenery/<int:scenery_id>/delete/', pilots.delete_scenery, name='delete_scenery'),

    # Resource
    path('resources/', resource.view_resources, name='resources'),
    path('resources/new/', resource.add_resource, name='new_resource'),
    path('resources/<int:resource_id>/edit/', resource.edit_resource, name='edit_resource'),
    path('resources/<int:resource_id>/delete/', resource.delete_resource, name='delete_resource'),

    # Training
    path('training/', training.view_training_center, name='training'),
    path('training/schedule/', training.request_training, name='request_training'),
    path('training/requests/', training.view_training_requests, name='training_requests'),
    path('training/requests/<int:request_id>/accept/', training.accept_training_request, name='accept_training'),
    path('training/requests/<int:request_id>/reject/', training.reject_training_request, name='reject_training'),
    path('training/requests/<int:request_id>/cancel/', training.cancel_training_request, name='cancel_training'),
    path('training/session/<int:session_id>/', training.view_session, name='view_session'),
    path('training/session/<int:session_id>/edit/', training.edit_session, name='edit_session'),
    path('training/session/<int:session_id>/file/', training.file_session, name='file_session'),
    path('training/mentors/', training.view_mentor_history, name='mentor_history'),
    path('training/scheduled/', training.view_scheduled_sessions, name='scheduled_sessions'),
    path('training/student/<int:cid>/', training.view_student_profile, name='student_profile'),

    # ULS (Auth)
    path('login/', uls.login, name='login'),
    path('logout/', uls.logout, name='logout'),

    # User
    path('staff/', user.view_staff, name='staff'),
    path('roster/', user.view_roster, name='roster'),
    path('roster/<int:cid>/', user.view_profile, name='view_user'),
    path('roster/<int:cid>/edit/', user.edit_user, name='edit_user'),
    path('roster/<int:cid>/editbio/', user.edit_bio, name='edit_bio'),
    path('roster/<int:cid>/editavatar/', user.edit_avatar, name='edit_avatar'),
    path('roster/<int:cid>/status/', user.update_status, name='edit_status'),
    path('roster/<int:cid>/addcomment/', user.add_comment, name='add_comment'),
    path('roster/<int:cid>/removecomment/', user.remove_comment, name='remove_comment'),
    path('roster/tidy/', user.view_inactive_users, name='roster_tidy'),
    path('roster/remove/', user.remove_users, name='remove_user'),

    # Views
    path('', views.view_homepage, name='home'),
    path('privacy/', views.view_privacy_policy, name='privacy'),
    path('calendar/', views.view_calendar, name='calendar'),

    # Visit
    path('visit/', visit.submit_visiting_request, name='visit'),
    path('visit/requests/', visit.view_visiting_requests, name='visit_requests'),
    path('visit/<int:visit_id>/accept/', visit.accept_visiting_request, name='accept_visit'),
    path('visit/<int:visit_id>/reject/', visit.reject_visiting_request, name='reject_visit'),

    path('django/', admin.site.urls),
]

# Allows access of media files such as documents and user profiles
urlpatterns += static(settings.MEDIA_URL, view=xframe_options_sameorigin(serve), document_root=settings.MEDIA_ROOT)

handler404 = 'apps.views.views.error_404'
handler500 = 'apps.views.views.error_500'
handler403 = 'apps.views.views.error_403'
handler400 = 'apps.views.views.error_400'

apps/training/models.py
from django.db import models
from ..user.models import User


TYPES = (
    (0, 'Classroom'),
    (1, 'Sweatbox'),
    (2, 'Online'),
    (3, 'OTS'),
)
LEVELS = (
    (0, 'Minor Ground'),
    (1, 'Major Ground'),
    (2, 'Minor Tower'),
    (3, 'Major Tower'),
    (4, 'Minor Approach'),
    (5, 'Major Approach'),
    (6, 'Center'),
    (7, 'Oceanic'),
)


class TrainingSession(models.Model):
    STATUSES = (
        (0, 'Scheduled'),
        (1, 'Completed'),
        (2, 'Cancelled'),
        (3, 'No-Show'),
    )
    OTS_STATUSES = (
        (0, 'Non-OTS'),
        (1, 'Passed'),
        (2, 'Failed'),
        (3, 'Recommended'),
    )
    student = models.ForeignKey(User, models.SET_NULL, null=True, blank=True, related_name='student_sessions')
    instructor = models.ForeignKey(User, models.SET_NULL, null=True, blank=True, related_name='instructor_sessions')
    start = models.DateTimeField()
    end = models.DateTimeField()
    movements = models.IntegerField(default=0)
    progress = models.IntegerField(default=3)
    position = models.CharField(max_length=16)
    type = models.IntegerField(choices=TYPES)
    level = models.IntegerField(choices=LEVELS)
    status = models.IntegerField(default=0, choices=STATUSES)
    ots_status = models.IntegerField(default=0, choices=OTS_STATUSES)
    ctrs_id = models.IntegerField(null=True, blank=True)
    notes = models.TextField(null=True, blank=True)
    solo_granted = models.BooleanField(default=False)

    @property
    def duration(self):
        return self.end - self.start

    def __str__(self):
        return f'{self.start} | {self.student.full_name} with {self.instructor.full_name}'


class TrainingRequest(models.Model):
    student = models.ForeignKey(User, models.CASCADE, related_name='training_requests')
    start = models.DateTimeField()
    end = models.DateTimeField()
    type = models.IntegerField(choices=TYPES)
    level = models.IntegerField(choices=LEVELS)
    remarks = models.TextField(null=True, blank=True)

    @property
    def duration(self):
        return self.end - self.start

    def __str__(self):
        return f'{self.student.full_name} | Training request for {self.get_level_display()}'

apps/training/templates/mentor_history.html
{% extends 'mainTemplate.html' %}

{% block body %}
    <div class="row">
        {% for tuple in mentors %}
            <div class="col-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-secondary">
                        <a class="float-right mt-3" data-toggle="collapse" href="#collapse-{{ forloop.counter }}"><i class="far fa-lg fa-plus"></i></a>
                        <h5 class="mb-0">{{ tuple.0 }}</h5>
                        <p class="mb-0">{{ tuple.1|length }} Session{{ tuple.1|length|pluralize }}</p>
                    </div>
                    <div class="collapse" id="collapse-{{ forloop.counter }}">
                        <div class="card-body">
                            <table class="table table-hover" style="width: 100%">
                                <thead>
                                    <th class="text-center" style="width: 23%">Student</th>
                                    <th class="text-center" style="width: 23%">Type</th>
                                    <th class="text-center" style="width: 23%">Level</th>
                                    <th class="text-center" style="width: 70%">Date</th>
                                </thead>
                                <tbody id="sessions">
                                    {% for session in tuple.1 %}
                                        <tr data-session="{{ session.id }}" style="cursor: pointer">
                                            <td class="text-center">{{ session.student.full_name }}</td>
                                            <td class="text-center">{{ session.get_type_display }}</td>
                                            <td class="text-center">{{ session.get_level_display }}</td>
                                            <td class="text-center">{{ session.start|date:'M j, Y @ Hi\z' }}</td>
                                        </tr>
                                    {% empty %}
                                        <td class="text-center" colspan="4">No sessions found!</td>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

{% block scripts %}
    <script>
        $('#sessions tr').click(function() {
            window.location.href = '{% url 'view_session' session_id=0 %}'.replace(/0/, $(this).data('session'))
        })
    </script>
{% endblock %}

apps/training/templates/scheduled_sessions.html
{% extends 'mainTemplate.html' %}
{% load filters %}

{% block body %}
    <div class="card">
        <div class="card-body text-center">
            <table id="sessions" class="table table-hover">
                <thead>
                    <tr>
                        <th class="text-center">Date / Time</th>
                        <th class="text-center">Level</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">Student</th>
                        <th class="text-center">Instructor</th>
                        <th class="text-center">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for session in sessions %}
                        <tr data-type="href" data-session="{{ session.id }}">
                            <td class="text-center" id="{{ session.id }}">
                                <span class="d-none">{{ session.start|timestamp }}</span>
                                <span id="date"></span><br>
                                <span class="text-black-50">({{ session.start|date:'M j, Y @ Hi\z' }})</span>
                            </td>
                            <td class="text-center">{{ session.get_level_display }}</td>
                            <td class="text-center">{{ session.get_type_display }}</td>
                            <td class="text-center">{{ session.student.full_name }}</td>
                            <td class="text-center">{{ session.instructor.full_name }}</td>
                            <td class="text-center"><span class="badge
                                {% if session.status == 0 %}badge-info
                                {% elif session.status == 1 %}badge-success
                                {% elif session.status == 2 %}badge-danger
                                {% elif session.status == 3 %}badge-warning
                                {% endif %}
                            ">{{ session.get_status_display }}</span></td>
                        </tr>
                    {% empty %}
                        <td class="text-center" colspan="5"><i>There are no scheduled training sessions...</i></td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://momentjs.com/downloads/moment.min.js"></script>
    <script src="https://momentjs.com/downloads/moment-timezone-with-data.min.js"></script>
    <script>
        let tz = moment.tz.guess()
        const sessions = {{ sessions_json|safe }}
        for (let id in sessions) {
            let start = moment.utc(sessions[id], 'YYYY-MM-DDThh:mm:ss')
            let end = moment.utc(sessions[id], 'YYYY-MM-DDTHH:mm:ss')
            $(`#${id} span#date`).text(start.tz(tz).format('MMM D, Y @ HHmm z'))
        }
        $(function() {
            $('#sessions').DataTable({
                pageLength: 10,
                lengthChange: false,
                order: [[ 0, 'desc' ]]
            })
        })
        $('#sessions tr[data-type="href"]').click(function() {
            window.location.href = '{% url 'view_session' session_id=0 %}'.replace(/0/, $(this).data('session'))
        })
    </script>
{% endblock %}

apps/training/templates/session.html
{% extends 'secondaryTemplate.html' %}
{% load filters %}

{% block header %}
    <h1 style="font-size: 60px">{{ session.student.first_name }}'s {{ session.get_level_display }} Session</h1>
    <span class="mb-3 badge badge-md {% if session.status == 0 %}badge-info{% elif session.status == 1 %}badge-success{% elif session.status == 2 %}badge-danger{% elif session.status == 3 %}badge-warning{% endif %}">
        {{ session.get_status_display }}
    </span>
    <h2 style="font-size: 30px"><i class="far fa-calendar-alt"></i> <span id="date"></span> <span id="zulu-date">({{ session.start|date:'M d, Y' }})</span></h2>
    <h2 style="font-size: 30px">
        <i class="far fa-clock"></i> <span id="start"></span> <i class="far fa-xs fa-long-arrow-right"></i> <span id="end"></span>
        ({{ session.start|date:'Hi\z' }} <i class="far fa-xs fa-long-arrow-right"></i> {{ session.end|date:'Hi\z' }})
    </h2>
{% endblock %}

{% block body %}
    {% if request.user_obj.is_staff or request.user_obj.is_mentor %}
        <div class="text-center text-lg-left mb-4">
        {% if session.status == 0 %}
            <a href="{% url 'file_session' session_id=session.id %}"><button class="btn btn-success"><i class="far fa-file-alt"></i> File Session</button></a>
        {% endif %}
            <a href="{% url 'edit_session' session_id=session.id %}"><button class="btn btn-secondary"><i class="far fa-pencil-ruler"></i> Edit Session</button></a>
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12 col-lg">
            <div class="row">
                <div class="col-lg">
                    <h3>Position</h3>
                    <p>{{ session.position|default:'None' }}</p>
                    <h3>Type</h3>
                    <p>{{ session.get_type_display }}</p>
                </div>
                <div class="col-lg">
                    <h3>Instructor</h3>
                    <p>{{ session.instructor.full_name }}</p>
                    <h3>Duration</h3>
                    <p>{{ session.duration|duration }}</p>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg">
            <h3>Session Notes</h3>
            <p>{{ session.notes|safe|default:'No notes provided.' }}</p>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    <script src="https://momentjs.com/downloads/moment.min.js"></script>
    <script src="https://momentjs.com/downloads/moment-timezone-with-data.min.js"></script>
    <script>
        let tz = moment.tz.guess()
        let start = moment.utc("{{ session.start|to_iso_format }}", 'YYYY-MM-DDThh:mm:ss')
        let end = moment.utc("{{ session.end|to_iso_format }}", 'YYYY-MM-DDTHH:mm:ss')
        $('span#date').text(start.tz(tz).format('MMM D, Y'))
        if (start.tz(tz).month() + 1 == "{{ session.start|date:'m' }}") {
            $('span#zulu-date').remove()
        }
        $('span#start').text(start.tz(tz).format('HHmm z'))
        $('span#end').text(end.tz(tz).format('HHmm z'))
    </script>
{% endblock %}

apps/training/templates/student_profile.html
{% extends 'mainTemplate.html' %}
{% load filters %}

{% block body %}
<div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">Endorsements</div>
                <div class="card-body">
                    <table class="table">
                        <tr>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">DEL</td>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">GND</td>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">TWR</td>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">APP</td>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">CTR</td>
                            <td style="width: 16.7%; font-size: 14px" class="text-center">OCN</td>
                        </tr>
                        <tr>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.del_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.del_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.del_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.gnd_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.gnd_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.gnd_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.twr_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.twr_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.twr_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.app_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.app_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.app_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.ctr_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.ctr_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.ctr_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                            <td style="width: 16.7%" class="text-center">
                                {% if student.ocn_cert == 3 %}<i class="fas fa-circle text-danger"></i>
                                {% elif student.ocn_cert == 2 %}<i class="fas fa-circle text-success"></i>
                                {% elif student.ocn_cert == 1 %}<i class="fas fa-circle text-warning"></i>
                                {% else %}<i class="fas fa-circle text-secondary"></i>
                                {% endif %}
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-6">
            <div class="card">
                <div class="card-header">Statistics</div>
                <div class="card-body px-5 d-flex justify-content-around">
                    <div class="text-center">
                        <h2 style="font-size: 25px">Sessions</h2>
                        <h1 style="font-size: 35px">{{ student.student_sessions.all|length|default:'<span class="text-muted">N/A</span>' }}</h1>
                    </div>
                    <div class="text-center">
                        <h2 style="font-size: 25px">Total Training Time</h2>
                        <h1 style="font-size: 35px">{{ training_time|duration|default:'<span class="text-muted">N/A</span>' }}</h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card">
        <div class="card-body text-center">
            <table id="sessions" class="table table-hover">
                <colgroup>
                    <col style="width: 30%">
                    <col style="width: 20%">
                    <col style="width: 15%">
                    <col style="width: 20%">
                    <col style="width: 15%">
                </colgroup>
                <thead>
                    <tr>
                        <th class="text-center">Date / Time</th>
                        <th class="text-center">Level</th>
                        <th class="text-center">Type</th>
                        <th class="text-center">Instructor</th>
                        <th class="text-center">Status</th>
                    </tr>
                </thead>
                <tbody>
                    {% for session in student.student_sessions.all %}
                        <tr data-type="href" data-session="{{ session.id }}">
                            <td class="text-center" id="{{ session.id }}">
                                <span class="d-none">{{ session.start|timestamp }}</span>
                                <span id="date"></span><br>
                                <span class="text-black-50">({{ session.start|date:'M j, Y @ Hi\z' }})</span>
                            </td>
                            <td class="text-center">{{ session.get_level_display }}</td>
                            <td class="text-center">{{ session.get_type_display }}</td>
                            <td class="text-center">{{ session.instructor.full_name }}</td>
                            <td class="text-center"><span class="badge
                                {% if session.status == 0 %}badge-info
                                {% elif session.status == 1 %}badge-success
                                {% elif session.status == 2 %}badge-danger
                                {% elif session.status == 3 %}badge-warning
                                {% endif %}
                            ">{{ session.get_status_display }}</span></td>
                        </tr>
                    {% empty %}
                        <td class="text-center" colspan="5"><i>This student has not had any sessions yet...</i></td>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://momentjs.com/downloads/moment.min.js"></script>
    <script src="https://momentjs.com/downloads/moment-timezone-with-data.min.js"></script>
    <script>
        let tz = moment.tz.guess()
        const sessions = {{ sessions_json|safe }}
        for (let id in sessions) {
            let start = moment.utc(sessions[id], 'YYYY-MM-DDThh:mm:ss')
            let end = moment.utc(sessions[id], 'YYYY-MM-DDTHH:mm:ss')
            $(`#${id} span#date`).text(start.tz(tz).format('MMM D, Y @ HHmm z'))
        }
        $(function() {
            $('#sessions').DataTable({
                pageLength: 10,
                lengthChange: false,
                order: [[ 0, 'desc' ]]
            })
        })
        $('#sessions tr[data-type="href"]').click(function() {
            window.location.href = '{% url 'view_session' session_id=0 %}'.replace(/0/, $(this).data('session'))
        })
    </script>
{% endblock %}